language: java
jdk:
    openjdk8
before_install:
     - rm ~/.m2/settings.xml
     - cp settings.xml ~/.m2
script: mvn clean install deploy
cache:
  directories:
    - $HOME/.m2
notifications:
  email:
    recipients:
      - group.ats.team@axway.com
    on_success: change
    on_failure: always
env:
   global:
     # sonatype username
     - secure: "J/LCQkA15taV1g+ReNhhEXmXVmfPcFtCivm8wGsgWWEcUUV5OabYmal/zB4DMquNchF/Pz9EsTudZEh//lc3H9A6Ddg+LxWmDVN1DO6Txmxz/yEnwrfQJskclBY1i2mLmCnMVuaZ/sebNqMlxPqjyr5MnbzgVhkIxqZMx9za0MBIJdju5ZZ1poxoAfgCXKjWbEYu5pxLEWnEL28wLvFvc9bZWcWLbkeOMUUeI+8kvLwQgeiWzSpzljkiNJnmdiFnPMSFVBcUgxIMXkcUgxgQmguDbVDVF2yCNQ1LJazSOb+DgfZovs2TQ/fNeaNclbWhTC79HD6J9lrRYqtIjdh3uRSoW7xzT0DEk0JUFsdTUzOjo2omEsoUa9572QKJx2/czMWwkKZQrmczgMLXg4zBvn1WZhEZmyiuWJuM4J8MjqGaTszcdQPTyyaH4P8oWjMgE7eHyZLVpL45UHBHquQJ7dMf/ZORLY7CoN/vNscPWpM/uzBU2+4ZhvHMUIF3oUdJEMdJ/UCOJMErLyoN63+3UJQAtd2S9Tmgolxd/s6anlrrNmBlgfmFMZ6RyRP1X0GnTXKVLOH5c8l4PDl/iqqM+MfBvfIF5xcRpNvivBYVCqAHfzDIKiazulqV9ZOLlgKvo2XNy/ItL7AXlNPR62044JlFPeD+7Fp9eHsh0GfZWhE="
     # sonatype password
     - secure: "FgJdISw6/D/z5qJHLou/KetDERa6kHSVGXCtwSXhruCvMnOZ7nIO2ScNtoflUsqHsQL/topk+6vCDvzqABmxQP2l7AfyVX0L0p+UYxz5fcLJo7iUJPi3E1j68TLvE4CCg4EwhvmGyQI9edxFQQ6pTlzFDrRtp6OPh/z990ALP+mHBt76QaDtUuTCAPo2a4F23d4OsHZmpCi0jwugPzsVcI5mrEc84YhNaxsBHOEhSb0M6NH+kXw7O86I+V9Gw42Vlrt3XO+ECC2NkHmY1kaTGUo2z26qBB/uhtRswdNZLWWgvJcpPuLucSfpUbPely4VI3Hkq5rdjbw6ZpSmdfa2ErX9HMrOzT1M/X7hbV1Pf/fXLvKEbSFmnUXG3jCziW8gdpdOK53/xtB+f5RHJfIMKVyIte3d4ULOi6MEjCIZKknJLkrcyc8ZvEU3grCAc/y0fy+k9BV2fgKANFB51z1G4CXSfaDOuvmaJ4MR74LqCzkTkbw8JVQznfee+E/61daScFFqx7daHMQrpDdLBRmC8uUKimMInhnypvJpjRQjY5fPr9rhnNDSY3aTiS/scxczGszTScKdyD1rdC4s4QqcSnoSaKrxj6fp2t39uveTL7ws+iyqtXFluGN0UT3xPQW8PxzMQJBYc6NNkfASrrh1SBG6cJdU9+GPIh7A/fXGAyg="
     

