language: java
jdk:
    openjdk8
before_install:
     - rm ~/.m2/settings.xml
     - cp settings.xml ~/.m2
script: mvn clean install deploy
cache:
  directories:
    - $HOME/.m2
notifications:
  email:
    recipients:
      - group.ats.team@axway.com
    on_success: change
    on_failure: always
env:
   global:
     # CI DEPLOY username
     - secure: "et1IXTBOiqE3dj/+8tng93obORJiiDpcsO5LOdLdKn1rorufisjjOt2ywjRiqL8R9QMqxbNHfFEz9qWnn5MZFmOgmAvbD1b7tpJMei7Cy2J03AvoS6dJSp9Dtdj7BGF+B5VUCcYB10D1Q6WO0mVDhuVWiP3A2MZvac428X3hbiW613tUltBRa+ZF3X6GcKARaRJxibH4IS3v3tk9nh8u+gh1Qdap/wbk2EstQYoeG1qUCEYj3jhv9psXHNZc+plOYfE1+zvsnHOAsX+UmumBCzcfiW7ZB0BfUtR7Q+9+W7u0+lkq8nj/0+K+7PWHNnNytfpYjn+AKyPYTSectcSCHfsQcNeKdln43QB4tJohtVRo8OOzKWYi/jSWp3X9eIqg1Qu63veRGN9oS7zeBa7QMgTNo9qwwW+RFiori5WYihOBnm+RBHx/9ef3WhxdI049f9jP01KB3ROFakifbAHDp28mRbfVsepnnyRRYeddbi9djTDZtDWesGkm55laCcP0YAdJbp+4KgAqiEAOGN1poh/k6SeBKaWsFO+UVIcSy1cqhxXbQMJyIrCcwI34aDhxiY3CMccwCVZVJW0zMSbhu6qnK8NDlTQR6GEamaDI/T0PhPoIzBg28NA1eiWw79T1eibsRRMIitQsKpq/cCHnWzE+6+XTc/WnemsSATkv2eU="
     # sonatype password
     - secure: "cuiCAIBWYNzkShvmTlkmXbk9HHWeEuNHYZM0aBOvhmDb3sw/8Zx6G1WJsGmeIzmKOI5hWe3TtJEH4EIhdzo5IWmdI5KtkTxMgiHUIWgRsZivcuQZljupoKom6iSVFSjeuNZdz9sKNaGU51G3iOOKUoQEwgqmyIrvGgGEPgBJ0npAN72Ojn8FJ2vTS3YaDciOzjT07FbUaczKgFEV6irIBf7I+dfmic+qTQnw9UgYrKAeZ4jWZ2p04vM/HUiI3PdYn3eFIcKj/8qAYV7UToSOvEIfv7WDUvE0yaKkVm0c9CwxHXO9biuklhGi/UBXFdj4UEqUL0ivWD0ZXmfFGLMq3lfwnpfPjUY8u1eVFYb6WD/gsD0q4pVPcB8Sp+qwTYL++EmASA4Zb1TZquoMbqO2tkO8dH2tLTo5AY+ZhTYCNbWcZ88U1qp2CfCuXv6NfP++w8voi+1cUVcLlDZMJoqxgN3fXjEiyACfWtIDCRKWh/35cQDoq+UoyuoISSo16NCKbnu/XnJv1secxK110vxDMzelTyGkl31gIxkEeEmgbJ6wOlQeKhqNONfvCvAFPJ4hYnuaYihc8vl3ueqesXy80bBdnRxdEyhN9+JBzC9MUvKAECP1kwV0ZhF1g+L8GbNAENkG3jIQLGjziXGFxZSzOHv8vQXx6/7lDVn1FeSVysY="     

