language: java
jdk:
    openjdk8
before_install:
     - rm ~/.m2/settings.xml
     - cp settings.xml ~/.m2
script: mvn clean install deploy
cache:
  directories:
    - $HOME/.m2
notifications:
  email:
    recipients:
      - group.ats.team@axway.com
    on_success: change
    on_failure: always
env:
   global:
     # sonatype username
     - secure: "J/LCQkA15taV1g+ReNhhEXmXVmfPcFtCivm8wGsgWWEcUUV5OabYmal/zB4DMquNchF/Pz9EsTudZEh//lc3H9A6Ddg+LxWmDVN1DO6Txmxz/yEnwrfQJskclBY1i2mLmCnMVuaZ/sebNqMlxPqjyr5MnbzgVhkIxqZMx9za0MBIJdju5ZZ1poxoAfgCXKjWbEYu5pxLEWnEL28wLvFvc9bZWcWLbkeOMUUeI+8kvLwQgeiWzSpzljkiNJnmdiFnPMSFVBcUgxIMXkcUgxgQmguDbVDVF2yCNQ1LJazSOb+DgfZovs2TQ/fNeaNclbWhTC79HD6J9lrRYqtIjdh3uRSoW7xzT0DEk0JUFsdTUzOjo2omEsoUa9572QKJx2/czMWwkKZQrmczgMLXg4zBvn1WZhEZmyiuWJuM4J8MjqGaTszcdQPTyyaH4P8oWjMgE7eHyZLVpL45UHBHquQJ7dMf/ZORLY7CoN/vNscPWpM/uzBU2+4ZhvHMUIF3oUdJEMdJ/UCOJMErLyoN63+3UJQAtd2S9Tmgolxd/s6anlrrNmBlgfmFMZ6RyRP1X0GnTXKVLOH5c8l4PDl/iqqM+MfBvfIF5xcRpNvivBYVCqAHfzDIKiazulqV9ZOLlgKvo2XNy/ItL7AXlNPR62044JlFPeD+7Fp9eHsh0GfZWhE="
     # sonatype password
     - secure: "BIbsrZVnECsjs1ITP4nJUn0NBBYr83rLbJldbR1YkEZA1p6SpCjck9L3x+zSldv/uiYu7PLkfG9QbWAk2y4RefT9PyK1dcx/HxfwOH9OxC9b7Hxx0+B1W5Wup5K1lZodZKYIHIy34qDZ22uAxVOepZQxzHGxcxGdLjTUtfediR9KAW1CZDPx32llAFZTXJvDkDmQfgWUg/mvjkSl4ApTKDP224n+kwYkUhED46KnHQkJlBUSxph9Z/aDc/xTX2sCEEH6cSQLLaaFMx+7nYWATGTZerpADwtLnbCixQ/JOdMSZFrQOH/In7/sEqds7rvkbeIkjMynfkON42l2Kq/SgiX2P+oV7G1e3gkW5IyKPw2zu1gR1CCuJO3BZCSSwoR+wwjiswrsIO1vijInqAMzt5QUJ0vu/RIaMyZOCOw4PKztQtzghyk7YUEBEpEwpzc30rhN9vE8bwKpTPcH38nn5Rm2n+nXHsPTfC//XVWnwO+bZCrWCbNNxpPY+S/n3YWxnj+xuA3Sisa4yJsTSU/8DCb5lA4phN9SunaVp0AXUQYXu6Svz/1vk9spum0hhrD6j2NU9vmvMCsvCmR17RqEy7bFiodIPw/TqsFZCPTupmQZSRvO1HDsB8IBOE9HNbFu6pG01Ij5BASXpBOxL/DQWiWJIbn0jEMzdoSf8T/OMkU="
     

